spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf8
    username: root
    password: 123456
  thymeleaf:
    cache: false


logging:
  config: classpath:config/logback.xml

